# When we get access to delta we can change this file to match what Jamie posted

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
data:
  fluentbit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info

    [INPUT]
        Name        tail
        Path        /var/applog/basic-app.log

    [OUTPUT]
        Name        file
        Match       *
        File        basic-app.outfile.log
        Path        /var/applog

#######################
# The following has been updated to the ConfigMap
#     [INPUT]
#         Path             /var/log/containers/*.log > /var/applog/basic-app.log
#     [OUTPUT]
#         Name             cloudwatch_logs > basic_app_cloudwatch_logs
########################

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: fluent-bit-{{ .Values.fluentbit.type }}
#   namespace: logging
#   labels:
#     template: fluent-bit-logging
# data:
#   fluent-bit.conf: |
#     [SERVICE]
#         Flush        5
#         Daemon       Off
#         Log_Level    info
#         Parsers_File parsers.conf
#         HTTP_Server  On
#         HTTP_Listen  0.0.0.0
#         HTTP_Port    2020
# {{- if eq .Values.fluentbit.type "application"}}
# {{ .Values.rawConfig | indent 4 }}
# {{- else }}
# {{ .Values.rawAuditConfig | indent 4 }}
# {{- end }}
# {{- if eq .Values.fluentbit.type "application"}}
#   input-kubernetes.conf: |
#     [INPUT]
#         Name             tail
#         Path             /var/applog/basic-app.log
#         Exclude_Path     /var/log/containers/*_openshift-*.log,/var/log/containers/*_kube-*.log,/var/log/containers/**_default_*.log*,/var/log/containers/*_logging_*.log
#         Multiline.Parser cri
#         Tag              kube.*
#         Refresh_Interval 10
#         Skip_Empty_Lines On
#         Read_from_Head   true
#         Mem_Buf_Limit    5MB
#         Skip_Long_Lines  On
#   fluent-bit-filter.conf: |
#     [FILTER]
#         Name                  multiline
#         Match                 kube.*
#         Multiline.Parser      java, python, go
#         multiline.key_content log
#     [FILTER]
#         Name                kubernetes
#         Match               kube.*
#         Kube_URL            https://kubernetes.default.svc.cluster.local:443
#         Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
#         Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
#         Merge_Log           On
#         Merge_Log_Key       log_processed
#         Merge_Log_Trim      On
#         keep_log            Off
#         K8S-Logging.Parser  On
#         K8S-Logging.Exclude Off
#         Buffer_Size         1MB
#         Kube_Tag_Prefix     kube.var.log.containers.
#         Labels              On
#         Annotations         Off
# {{- else }}
#   input-kubernetes.conf: |
#     [INPUT]
#         Name             tail
#         Path             /var/log/kube-apiserver/audit.log
#         Parser           json
#         Refresh_Interval 10
#         Mem_Buf_Limit    5MB
#         Skip_Long_Lines  On
# {{- end }}
#   fluent-bit-output.conf: |
#     [OUTPUT]
#         Name  basic_app_cloudwatch_logs
#         Match *
#         region {{ .Values.region }}
#         log_group_name {{ .Values.output.cloudwatch.loggroup }}
#         log_stream_name {{ .Values.output.cloudwatch.logstream }}
#         auto_create_group false
#   parsers.conf: |
#     [PARSER]
#         Name        docker
#         Format      json
#         Time_Key    time
#         Time_Format %Y-%m-%dT%H:%M:%S.%L
#         Time_Keep   On
#     [PARSER]
#         Name        json
#         Format      json
#         Time_Key    time
#         Time_Format %d/%b/%Y:%H:%M:%S %z
#     [PARSER]
#         Name        cri
#         Format      regex
#         Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
#         Time_Key    time
#         Time_Format %Y-%m-%dT%H:%M:%S.%L%z


